language: python
python:
- 3.7-dev
addons:
  ssh_known_hosts:
  - proxy8.transport-intelligence.com:9022
  - www-int2.transport-search.org
  - www2-int2.transport-search.org
before_script:
- echo -e "Host tiproxy8\n\tHostName ${TIPRX_SVR}\n\tPort ${TIPRX_PRT}\n\tForwardAgent yes" >> ~/.ssh/config
- echo -e "Host titsc\n\tHostName ${TITSC_SVR}\n\tProxyCommand ssh -W %h:22 qa@tiproxy8" >> ~/.ssh/config
- echo -e "Host titscnew\n\tHostName ${TITSCNEW_SVR}\n\tProxyCommand ssh -W %h:22 qa@tiproxy8" >> ~/.ssh/config
install:
- pip install -r requirements.txt
script: make PY_EXEC=python checkers
before_deploy:
- openssl aes-256-cbc -K $encrypted_9cd66a2ab98f_key -iv $encrypted_9cd66a2ab98f_iv
  -in id_rsa.travis-ci-deploy.enc -out /tmp/id_rsa.travis-ci-deploy -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/id_rsa.travis-ci-deploy
- ssh-add /tmp/id_rsa.travis-ci-deploy
deploy:
- provider: script
  skip_cleanup: true
  script: bash ci-scripts/deploy.sh
  on:
    branch: master

